name: OnIssue

on:
  issues:
    types: [opened]

jobs:
  echo-details:
    runs-on: ubuntu-latest
    steps:
      - name: Print Issue Details
        run: echo "${{toJSON(github.event.issue.body)}}"
